config/routes.rb
Rails.application.routes.draw do
  get 'downgrade/new'

  get 'wikis/index'

  get 'wikis/show'

  get 'wikis/new'

  get 'wikis/edit'

  resources :wikis

  devise_for :users

  get 'about' => 'welcome#about'

  root 'welcome#index'
  
  resources :charges, only: [:new, :create]

  resources :downgrade, only: [:new, :create]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
   enum role: [:standard, :premium, :admin]
   after_initialize :set_default_role
   after_update :wikis_to_public, if :standard

   has_many :wikis, dependent: :destroy
   has_many :collaborators, dependent: :destroy
  
   def set_default_role
     self.role ||= :standard
   end

   def wikis_to_public
     return unless role_was == 'premium' && role == 'standard'
     wikis.update_all(private: false)
   end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  validates :user, presence: true

  has_many :users, through: :collaborators
  has_many :collaborators, dependent: :destroy

  before_create :set_to_false_private

  def set_to_false_private
     self.private ||= false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base	
  #before_action :authenticate_user!
  protect_from_forgery with: :exception  
  
  include Pundit
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
 def create
   # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
 
   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: Amount.default,
     description: "BigMoney Membership - #{current_user.email}",
     currency: 'usd'
   )
 
   flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
   redirect_to user_path(current_user) # or wherever
 
   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
 end

 def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "BigMoney Membership - #{current_user.name}",
     amount: Amount.default
   }
 end
end 

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def new
    @collaborator = Collaborator.new
  end

  def create
    @collaborator_user = User.find_by_email(params[:collaborator])
    @wiki = Wiki.find(params[:wiki_id])

    if @wiki.collaborators.exists?(user_id: @collaborator_user.id)
      flash[:notice] = "#{@collaborator_user.email} is already a collaborator."
      redirect_to edit_wiki_path(@wiki)
    else
      @collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: @collaborator_user.id)
      if @collaborator.save
        flash[:notice] = "#{@collaborator_user.email} was added as a collaborator."
        redirect_to edit_wiki_path(@wiki)
      else
        flash[:alert] = "There was an error adding this collaborator. Please try again."
        redirect_to edit_wiki_path(@wiki)
      end
    end
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.find(params[:id])
    @collaborator_user = User.find(@collaborator.user_id)

    if @collaborator.destroy
      flash[:notice] = "#{@collaborator_user.email} was removed as a collaborator."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:alert] = "There was an error removing this collaborator. Please try again."
      redirect_to edit_wiki_path(@wiki)
    end
  end
end

app/controllers/downgrade_controller.rb
class DowngradeController < ApplicationController
    def new
    end
    
    def create        	
        current_user.update_attribute(:role, :standard)
        
        flash[:notice] = "You have successfully downgraded your account. Your private wikis are now public wikis."
        
        redirect_to root_path
    end
end

app/controllers/downgrade_controller_controller.rb
class DowngradeController < ApplicationController
    def new
    end
    
    def create
        current_user.update_attribute(:standard, true)
        current_user.update_attribute(:premium, false)
        
        flash[:notice] = "You have successfully downgraded your account."
        
        redirect_to root_path
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
  	@wikis = policy_scope(Wiki)
    authorize @wiki
    @wikis = Wiki.visible_to(current_user)      
  end

  def show
    @wiki = Wiki.find(params[:id]) 
    authorize @wiki

    unless (@wiki.private == false) || current_user.premium? || current_user.admin?
        flash[:alert] = "You must be a premium user to view private topics."
        if current_user
          redirect_to new_charge_path
        else
          redirect_to new_user_registration_path
        end
    end    	
  end

  def new
  	@wiki = Wiki.new
    authorize @wiki
  end

  def create
     @wiki = Wiki.new(wiki_params)
     @wiki.user = current_user
     authorize @wiki

     if @wiki.save
       flash[:notice] = "Wiki was saved."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :new
     end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
     @wiki = Wiki.find(params[:id])
     authorize @wiki
     @wiki.assign_attributes(wiki_params) 
     
     if @wiki.save
       flash[:notice] = "Wiki was updated."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :edit
     end
  end

  def destroy
     @wiki = Wiki.find(params[:id])
     authorize @wiki

     if @wiki.destroy
       flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
       redirect_to wikis_path
     else
       flash.now[:alert] = "There was an error deleting the wiki."
       render :show
     end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end    
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    require 'redcarpet'
    renderer = Redcarpet::Render::HTML.new
    extensions = { :autolink => true }
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/downgrade_controller_helper.rb
module DowngradeControllerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/collaborators/_form.html.erb
<% if @wiki.user_id == current_user.id || current_user.admin? %>
 		<div class="form-group">
			<% @users.each do |user| %>
				<h4><%= user.email %> </h4>

				<% if @wiki.users.include? user %>
					<div>
					<%= link_to "Remove Collaborator", wiki_collaborator_path(@wiki, @wiki.collaborators.find_by_user_id(user.id).id), method: :delete, class: 'btn btn-danger' %>
				  </div>
				<% else %>
					<div>
					<%= link_to "Add Collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: 'btn btn-info' %>
					</div>
				<% end %>
			<% end %>
 		</div>
 
 <% end %>

app/views/downgrade/new.html.erb
<h4>Click to downgrade your account</h4>
<%= link_to "Downgrade Your Account", downgrade_create_path, method: :create, data: {confirm: 'Are you sure you want to downgrade? Private wikis will become public.'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
       <li><%= link_to "Home", root_path %></li>
       <li><%= link_to "About", about_path %></li>
       <li><%= link_to "Wikis", wikis_path %></li>       
    </ul>

       <% if flash[:notice] %>
         <div>
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:alert] %>
         <div>
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

    <%= yield %>
	  </br>

    <% if user_signed_in? %>
	   Signed in as: <strong><%= current_user.email %></strong> |
	   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	  <% else %>
	   <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
	   <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
	  <% end %>
    </br>
    
    <% if current_user.standard? %>
     <%= link_to 'Upgrade to Premium', new_charge_path, :class => 'navbar-link' %>
    <% elsif current_user.premium? %>
     <%= link_to 'Downgrade Your Account', new_downgrade_path, :class => 'navbar-link' %></li>
    <% end %>   
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/_form.html.erb
 <%= form_for @wiki do |f| %>
   <%= f.label :title %>
   <%= f.text_field :title %>
 
   <%= f.label :body %>
   <%= f.text_area :body %>

   <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
     <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
     <% end %>
    </div>
   <% end %>
   <% if @wiki.private %>
     <%= render partial: 'collaborators/form', locals: { f: f } %>
  <% end %>
   <%= f.submit "Save" %>
<% end %>   

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
  <%= render partial: 'form', locals: { wiki: @wiki } %>

app/views/wikis/index.html.erb
 <hr>
 <h1>All Wikis</h1>
 <b><%= link_to "Create a Wiki", markdown(new_wiki_path) %></b>
 <hr>
 </br>
 <% @wikis.each do |wiki| %>
   <p><%= link_to markdown(wiki.title), wiki %></p>
 <% end %>
 </br>
 <hr>

app/views/wikis/new.html.erb
<h1>Create a Wiki</h1>
  <%= render partial: 'form', locals: { wiki: @wiki } %>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
<p><%= @wiki.body %></p>
<div>
<% if policy(@wiki).update? %>	
 <%= link_to "Edit", edit_wiki_path(@wiki) %>
<% end %>
 <% if policy(@wiki).update? %>
 <%= link_to "Delete Wiki", @wiki, method: :delete, data: {confirm: 'Are you sure you want to delete this wiki?'} %>
<% end %> 
</div>